version: 0.2
phases:
  build:
    commands:
      - echo "Starting Drift Detection"
      - drift_detection_id=$(aws cloudformation detect-stack-drift --stack-name lambda-s3-put-notification --query StackDriftDetectionId --output text)
      - echo "Drift Detection ID - ${drift_detection_id}"
      - aws cloudformation wait stack-drift-detection-complete --stack-drift-detection-id ${drift_detection_id}
      - aws cloudformation describe-stack-drift-detection-status --stack-drift-detection-id ${drift_detection_id} --query DetectionStatus --output text

cache:
  paths:
    - '/root/.cache/pip'
