version: 0.2
phases:
  build:
    commands:
      - echo "Starting Drift Detection"
      - drift_detection_id=$(aws cloudformation detect-stack-drift --stack-name lambda-s3-put-notification --query StackDriftDetectionId --output text)
cache:
  paths:
    - '/root/.cache/pip'
