name: CloudFormation Lint and Guard

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/*"
#  pull_request:
#    branches:
#      - 'main'

jobs:
  lint-and-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Install cfn-guard
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
          ls -l /tmp
          ls -l ~/.guard/bin/cfn-guard
      - name: Run cfn-lint
        run: cfn-lint template.yaml

      - name: Run cfn-guard
        run: ~/.guard/bin/cfn-guard validate -r ruleset.guard -d template.yaml
